CREATE TABLE tb_user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    userpassword VARCHAR(255) NOT NULL,
    sex ENUM('M', 'F', 'O', 'UNKNOWN') DEFAULT 'UNKNOWN',
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
